todo/urls.py
from django.urls import path
from . import views

app_name = 'todo'

urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.addToDo, name='add'),
    path('complete/<int:todo_id>/', views.completeToDo, name='complete'),
    path('deletecompleted/', views.deleteCompleted, name='deletecompleted'),
    path('deleteall/', views.deleteAll, name='deleteall'),
]

todoproj/urls.py
from django.contrib import admin
from django.urls import path, include

from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls')),
    path('', RedirectView.as_view(url='/todo/', permanent=True)),
]

todo/models.py
from django.db import models


# Create your models here.
class ToDo(models.Model):
    text = models.CharField(max_length=255)
    complete = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.text

    class Meta:
        verbose_name_plural = 'todos'
        verbose_name = 'todo'

todo/forms.py
from django import forms


class ToDoForm(forms.Form):
    text = forms.CharField(max_length=255, widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Enter TO-DO Item here... e.g. Remind Aniket to practice DJango',
            'aria-label': 'ToDo Item Text',
            'aria-describedby': 'basic-addon2',
        }
    ))

todo/views.py
from django.shortcuts import render
from django.http.response import HttpResponseRedirect
from django.views.decorators.http import require_POST
from .models import ToDo
from .forms import ToDoForm


# Create your views here.
def index(request):
    form = ToDoForm()
    todos = ToDo.objects.order_by('-created_at')
    return render(request, 'todo/index.html', {'todos': todos, 'form': form})


@require_POST
def addToDo(request):
    form = ToDoForm(request.POST)

    if form.is_valid():
        new_todo = ToDo(text=request.POST['text'])
        new_todo.save()

    return HttpResponseRedirect('/')


def completeToDo(request, todo_id):
    todo = ToDo.objects.get(id=todo_id)
    todo.complete = True
    todo.save()
    return HttpResponseRedirect('/')


def deleteCompleted(request):
    ToDo.objects.filter(complete__exact=True).delete()
    return HttpResponseRedirect('/')


def deleteAll(request):
    ToDo.objects.all().delete()
    return HttpResponseRedirect('/')

todo/templates/todo/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ToDo App</title>
    <link href="https://fonts.googleapis.com/css?family=Oswald" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/bootswatch/4.0.0-beta.3/flatly/bootstrap.min.css" rel="stylesheet" integrity="sha384-+lmTKXkS+c9d34U9obDdGOZT7zqFicJDkhckYYsW7oenXR37T2OEV4uqfUO45M87"
        crossorigin="anonymous"> {% load static %}
    <link rel="stylesheet" href="{% static 'todo/styles.css' %}" />
</head>

<body>
    <div class="container wrapper">
        <div class="row">
            <div class="col-md-12" id="content">
                <h2>Manage your TO-DO List here:</h2>

                <form action="{% url 'todo:add' %}" method="POST" role="form">
                    {% csrf_token %}
                    <div class="form-group">
                        <div class="input-group mb-3">
                            <!--<input type="text" class="form-control"
                               placeholder="Enter TO-DO Item here... e.g. Delete Junk Files from laptop"
                               aria-label="Recipient's username" aria-describedby="basic-addon2">-->
                            {{ form.text }}
                            <div class="input-group-append">
                                <button class="btn btn-outline-secondary the-icons" type="submit">ADD</button>
                            </div>
                        </div>
                    </div>
                </form>

                <div class="row t10">
                    <div class="col-lg-12">
                        <div class="btn-toolbar">
                            <div class="btn-group">
                                <a href="{% url 'todo:deletecompleted' %}">
                                    <button type="button" class="btn btn-warning the-icons">
                                        <span class="glyphicon glyphicon-trash the-icons"></span> DELETE COMPLETED
                                    </button>
                                </a>
                                <a href="{% url 'todo:deleteall' %}">
                                    <button type="button" class="ml-2 btn btn-warning the-icons">
                                        <span class="glyphicon glyphicon-trash the-icons"></span> DELETE ALL
                                    </button>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card t20">
                    <ul class="list-group list-group-flush">
                        {% for todo in todos %} {% if todo.complete %}
                        <li class="list-group-item todo-completed">{{ todo.text }}</li>
                        {% else %}
                        <a href="{% url 'todo:complete' todo.id %}">
                            <li class="list-group-item">{{ todo.text }}</li>
                        </a>
                        {% endif %} {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <footer>
            <div class="row pad">
                <div class="col-md-12 text-center">Copyright&copy; 2018 ToDo App - Aniket Aryamane</div>
            </div>
        </footer>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!-- Bootstrap JavaScript -->
    <script src="{% static 'todo/bs/js/bootstrap.min.js' %}"></script>
</body>

</html>